exempli gratia: e.g.

- solution of a Differential Equations (DE) is a function, not value.

* Statistics:
** Data:
                Nominal Data                Interval / Ratio Data
                ━━━━━━━━━━━━━━━━━━━━     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
               ┃  +-----------------+ ┃   ┃                                    +-------------------+ ┃
               ┃  | Test for        | ┃   ┃                                    | Test for a mean   | ┃
               ┃  | Proportion      | ┃   ┃                                    |                   | ┃
               ┃  +-----------------+ ┃   ┃                                    +-------------------+ ┃
               ┃                      ┃   ┃                                                          ┃
               ┃  +-----------------+ ┃   ┃ +-------------------------+                              ┃
               ┃  | Difference of   | ┃   ┃ | difference of two means |                              ┃
               ┃  | two proportions | ┃   ┃ | (independent samples)   |                              ┃
               ┃  +-----------------+ ┃   ┃ +-------------------------+                              ┃
               ┃                      ┃   ┃                                                          ┃
               ┃  +-----------------+ ┃   ┃ +-------------------------+        +-------------------+ ┃
               ┃  | Chi-sq test for | ┃   ┃ | Regression analysis     |        | Difference of two | ┃
               ┃  | independence    | ┃   ┃ |                         |        | means (paired)    | ┃
               ┃  +-----------------+ ┃   ┃ +-------------------------+        +-------------------+ ┃
                ━━━━━━━━━━━━━━━━━━━━     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

** Samples:
                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 One           ┃  +-----------------+                                          +-------------------+ ┃
 Sample        ┃  | Test for        |                                          | Test for a mean   | ┃
               ┃  | Proportion      |                                          |                   | ┃
               ┃  +-----------------+                                          +-------------------+ ┃
                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 Two           ┃  +-----------------+       +-------------------------+                              ┃
 Samples       ┃  | Difference of   |       | difference of two means |                              ┃
               ┃  | two proportions |       | (independent samples)   |                              ┃
               ┃  +-----------------+       +-------------------------+                              ┃
                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 One           ┃  +-----------------+       +-------------------------+        +-------------------+ ┃
 Sample,       ┃  | Chi-sq test for |       | Regression analysis     |        | Difference of two | ┃
 Two           ┃  | independence    |       |                         |        | means (paired)    | ┃
 Measures      ┃  +-----------------+       +-------------------------+        +-------------------+ ┃
                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

** Purpose:
                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Testing      ┃  +-----------------+                                          +-------------------+ ┃
  against      ┃  | Test for        |                                          | Test for a mean   | ┃
  a value      ┃  | Proportion      |                                          |                   | ┃
               ┃  +-----------------+                                          +-------------------+ ┃
                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━                         ┃
                                                                            ┃                        ┃
                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━    ┃                        ┃
 Comparing     ┃  +-----------------+       +-------------------------+  ┃  ┃                        ┃
  two          ┃  | Difference of   |       | difference of two means |  ┃  ┃                        ┃
 statistics    ┃  | two proportions |       | (independent samples)   |  ┃  ┃                        ┃
               ┃  +-----------------+       +-------------------------+  ┃  ┃                        ┃
                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━    ┃                        ┃
                                                                            ┃                        ┃
                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━    ┃                        ┃
 Looking       ┃  +-----------------+       +-------------------------+  ┃  ┃  +-------------------+ ┃
 for           ┃  | Chi-sq test for |       | Regression analysis     |  ┃  ┃  | Difference of two | ┃
 relationships ┃  | independence    |       |                         |  ┃  ┃  | means (paired)    | ┃
               ┃  +-----------------+       +-------------------------+  ┃  ┃  +-------------------+ ┃
                ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━    ━━━━━━━━━━━━━━━━━━━━━━






* hierarchy:
** what is needed to understand X:
   a big tree and paths through this tree
** where leads understanding of X1, X2, .. Xn:
   prospects, applications in other science fields, everyday life etc.
** what's the next step:
   why to study Z and not W after understanding X1, X2 .. Xn in dependency of the field of some interest
* WebApp, Datomic/Keystore (timestamps)/ Clojurescript
* Start with http://eu.ixl.com/
* Take a look at
** Knowledge Map: https://www.khanacademy.org/exercisedashboard




http://www.gametheory.net/
** http://www.reddit.com/r/math
** Ask:
   Andreas http://www.reddit.com/r/actuary
   Christofer


* Game Theory: Nash Equilibrum (NE):
  Each players best response to the others
  Nobody has an incentive to deviate from their actions if an equilibrum is played

* TODO
1. write down action profiles for everyone (the matrix) and calculate optimal mixed strategies for everyone in order to get NE
2. Calculate maxmin strategy and maxmin value (i.e. when the other guys do max harm the i-guy)
** games beyond 2x2 (See the 2-4 Hardness lecture):
   Linear Complementarity formulation
   Support Enumeration Method
* Go over the book from the Prof. from Karlsruhe
* Higher order logic


* Hypotheses, Conjectures & Theorems:
** Goldbach conjencture: ∀ (Every) even integer ≧ 2 is a ∑ of two primes
** Riemann hypothesis: The real part of every non-trivila zero of the Zeta function is 1/2 (prime numbers)
** Poincare conjencture: ∀ (Every) simply connected, closed 3-manifold is homeomorfic to the 3-sphere (Donuts)
** P vs. NP: ∀ problem whose solution can be quickly verified by a computer can also be quickly solved by a computer
** Fermant's Last Theorem: ∀ (For all) n ≧ 2 ∉ (there's no) x,y,z such that xⁿ + yⁿ = zⁿ
** Continuum Hypothesis: There is no set whose cardinality is strictly between that of the integers and that of the real numbers.
   Notes: R surj P(N) (Power series - Mocninovy rad)
** Fundamental Theorem of Arithmetics: Every positive integer n can be written in a unique way as a product of primes.

* Morphisms:
** Category is:
*** A collection of arrows and morphism that can be composed if they are adjacent.
*** A structure packing structures of the same type (same category) and structure preserving mappings between them.

*** Quadruple: CAT = (O, hom, id, ◦) consisting of
**** O  : class of CAT-objects: Ob(A); e.g. A,B are CAT-objects
**** hom: set of CAT-morphisms: hom(A, B) = {f | f: A -> B } (e.g. arrows)
     (class of all CAT-morphisms: Mor(CAT) = Union of all sets hom(A,B) in CAT)
**** id : set of identity morphisms for every CAT-object
**** ◦  : morphism composition: hom(a, b) × hom(b, c) → hom(a, c): g ◦ f; it's a partialy binary operation on Mor(CAT::)



   - třídy objektů ob(C)
   - třídy morfismů hom(C)
   - skládání morfismů: hom(a, b) × hom(b, c) → hom(a, c): g o f

**
| Set theory                  | Category theory                          |
|-----------------------------+------------------------------------------|
| membership relation         | -                                        |
| sets                        | categories                               |
| elements                    | objects                                  |
| -                           | morphisms (structure-preserving mapping) |
| functions                   | functors                                 |
| equations between elements  | isomorphisms between objects             |
| equations between sets      | equivalences between categories          |
| equations between functions | natural transformations between functors |


* Isomorphism f: X -> Y
  ∃ a function g: Y -> X such that g ∘ f = idX and f ∘ g = idY
  (f is invertible and g is the inverse of f)

** Category theory - Modeling (new vocabulary)
   | Hierarchies                | partial orders |
   | symmetries                 | group elements |
   | data models                | categories     |
   | agent actions              | monoid actions |
   | local-to-global principles | sheaves        |
   | self-similarity            | operads        |
   | context                    | monads         |


** Catergory of sets (Set)

Hom-Set(X, Y): the set of functions X -> Y

** olog = ontology log

Different branches of mathematics can be formalized
into categories. These categories can then be connected together by functors. And the
sense in which these functors provide powerful communication of ideas is that facts and
theorems proven in one category can be transferred through a connecting functor to
yield proofs of an analogous theorem in another category. A functor is like a conductor
of mathematical truth.


* Mappings: X -> Y (Zobrazenia):
** Surjection: every elem in Y is "used";                           |X| ≥ |Y| (onto; "at least as big")
** Injective:  distinct Xs -> distinc Ys;                           |X| ≤ |Y| (? one-to-one ?)
** Bijection:  exact pairing between X, Y;                          |X| = |Y| (vzajomne jednoznacne zobrazenie, "same size")
** Strict:     Surjection from X to Y but no bijection from Y to X; |X| < |Y| (? double usage of some Ys ?, "strictly bigger")


* Probability:
** Probability rules:
Difference Rule: P(B − A) = P(B) - P(A ∩ B)
Inclusion-Exclusion: P(A ∪ B) = P(A) + P(B) − P(A ∩ B)
Boole’s Inequality: P(A ∪ B) <= P(A) + P(B)
Monotonicity: If A ⊆ B then P(A) <= P(B)

** Ordinary conditional probability P(A ∣ B) = P(A ∩ B) / P(B):

| Objective Health | Objective Health | Test result  | Test result | Outcome probability | Event T ∩ H:                      |
| ill / healthy    |      probability |              | probability |            P(T ∩ H) | P(T ∣ H ) =                       |
| H                |             P(H) | T            |        P(T) |       (* P(H) P(T)) | (/ P(T ∩ H) P(H))                 |
|------------------+------------------+--------------+-------------+---------------------+-----------------------------------|
| really-ill       |              0.1 | test-ill     |         0.9 |                0.09 | (/ 0.09 (+ 0.09 0.27)) = 0.25     |
| really-ill       |              0.1 | test-healthy |         0.1 |                0.01 | (/ 0.01 (+ 0.01 0.63)) = 0.015625 |
| really-healthy   |              0.9 | test-ill     |         0.3 |                0.27 | (/ 0.27 (+ 0.09 0.27)) = 0.75     |
| really-healthy   |              0.9 | test-healthy |         0.7 |                0.63 | (/ 0.63 (+ 0.01 0.63)) = 0.984375 |

- Generall test correctness: 0.09 + 0.63 = 0.72 (i.e. proper results for ill + proper results for healthy persons)
- Just guessing "everybody's healthy" gives 90% "generall test correctness" because the test is wrong only for ill patients and they make up 10% of the population.


# ----------------------------------------
#		       test positive
#                   +---- 0.9            0.1 * 0.9 = 0.09
#          ill      |
#    +---- 0.1 -----+
#    |              |  test negative
#    |              +---- 0.1            0.1 * 0.1 = 0.01
#    |
#    |
#  ---+                test positive
#    |              +---- 0.3            0.9 * 0.3 = 0.27
#    |              |
#    +--- 0.9 ------+
#       healthy     |
#                   |  test negative
#                   +---- 0.7            0.9 * 0.7 = 0.63

;; test is negative i.e. says "you're healthy" and the patient is really ill (has the condition)
(/ 0.01 (+ 0.01 0.63)) = 0.015625

;; test is positive i.e. says "you're ill" and the patient is really ill (has the condition)
(/ 0.09 (+ 0.09 0.27)) = 0.25

;; test is negative i.e. says "you're healthy" and the patient is really health (doesn't have the condition)y
(/ 0.63 (+ 0.01 0.63)) = 0.984375

;; test is posivite i.e. says "you're ill" and the patient is really healthy (doesn't have the condition)
(/ 0.27 (+ 0.09 0.27)) = 0.75

** A posteriori conditional probability P(B ∣ A) = P(A ∩ B) / P(B):
   if event B precedes event A in time. Example: The probability it was cloudy this morning, given that it rained in the afternoon.




* unicode utf-8:
  (defun ucs-insert-char ()
  (interactive)
  (insert "∣"))

  (global-set-key [f10] 'ucs-insert-char)


	0x00	0x01	0x02	0x03	0x04	0x05	0x06	0x07	0x08	0x09	0x0A	0x0B	0x0C	0x0D	0x0E	0x0F
U+00Bx			x²	x³						x¹
U+207x	x⁰	xⁱ			x⁴	x⁵	x⁶	x⁷	x⁸	x⁹	x⁺	x⁻	x⁼	x⁽	x⁾	xⁿ
U+208x	x₀	x₁	x₂	x₃	x₄	x₅	x₆	x₇	x₈	x₉	x₊	x₋	x₌	x₍	x₎
U+209x	xₐ	xₑ	xₒ	xₓ	xₔ	xₕ	xₖ	xₗ	xₘ	xₙ	xₚ	xₛ	xₜ

	0x00	0x01	0x02	0x03	0x04	0x05	0x06	0x07	0x08	0x09	0x0A	0x0B	0x0C	0x0D	0x0E	0x0F
0x2190	←	↑	→	↓	↔	↕	↖	↗	↘	↙	↚	↛	↜	↝	↞	↟
0x21a0	↠	↡	↢	↣	↤	↥	↦	↧	↨	↩	↪	↫	↬	↭	↮	↯
0x21b0	↰	↱	↲	↳	↴	↵	↶	↷	↸	↹	↺	↻	↼	↽	↾	↿
0x21c0	⇀	⇁	⇂	⇃	⇄	⇅	⇆	⇇	⇈	⇉	⇊	⇋	⇌	⇍	⇎	⇏
0x21d0	⇐	⇑	⇒	⇓	⇔	⇕	⇖	⇗	⇘	⇙	⇚	⇛	⇜	⇝	⇞	⇟
0x21e0	⇠	⇡	⇢	⇣	⇤	⇥	⇦	⇧	⇨	⇩	⇪	⇫	⇬	⇭	⇮	⇯
0x21f0	⇰	⇱	⇲	⇳	⇴	⇵	⇶	⇷	⇸	⇹	⇺	⇻	⇼	⇽	⇾	⇿


	0x00	0x01	0x02	0x03	0x04	0x05	0x06	0x07	0x08	0x09	0x0A	0x0B	0x0C	0x0D	0x0E	0x0F
U+220x	∀	∁	∂	∃	∄	∅	∆	∇	∈	∉	∊	∋	∌	∍	∎	∏
U+221x	∐	∑	−	∓	∔	∕	∖	∗	∘	∙	√	∛	∜	∝	∞	∟
U+222x	∠	∡	∢	∣	∤	∥	∦	∧	∨	∩	∪	∫	∬	∭	∮	∯
U+223x	∰	∱	∲	∳	∴	∵	∶	∷	∸	∹	∺	∻	∼	∽	∾	∿
U+224x	≀	≁	≂	≃	≄	≅	≆	≇	≈	≉	≊	≋	≌	≍	≎	≏
U+225x	≐	≑	≒	≓	≔	≕	≖	≗	≘	≙	≚	≛	≜	≝	≞	≟
U+226x	≠	≡	≢	≣	≤	≥	≦	≧	≨	≩	≪	≫	≬	≭	≮	≯
U+227x	≰	≱	≲	≳	≴	≵	≶	≷	≸	≹	≺	≻	≼	≽	≾	≿
U+228x	⊀	⊁	⊂	⊃	⊄	⊅	⊆	⊇	⊈	⊉	⊊	⊋	⊌	⊍	⊎	⊏
U+229x	⊐	⊑	⊒	⊓	⊔	⊕	⊖	⊗	⊘	⊙	⊚	⊛	⊜	⊝	⊞	⊟
U+22Ax	⊠	⊡	⊢	⊣	⊤	⊥	⊦	⊧	⊨	⊩	⊪	⊫	⊬	⊭	⊮	⊯
U+22Bx	⊰	⊱	⊲	⊳	⊴	⊵	⊶	⊷	⊸	⊹	⊺	⊻	⊼	⊽	⊾	⊿
U+22Cx	⋀	⋁	⋂	⋃	⋄	⋅	⋆	⋇	⋈	⋉	⋊	⋋	⋌	⋍	⋎	⋏
U+22Dx	⋐	⋑	⋒	⋓	⋔	⋕	⋖	⋗	⋘	⋙	⋚	⋛	⋜	⋝	⋞	⋟
U+22Ex	⋠	⋡	⋢	⋣	⋤	⋥	⋦	⋧	⋨	⋩	⋪	⋫	⋬	⋭	⋮	⋯
U+22Fx	⋰	⋱	⋲	⋳	⋴	⋵	⋶	⋷	⋸	⋹	⋺	⋻	⋼	⋽	⋾	⋿


	0x00	0x01	0x02	0x03	0x04	0x05	0x06	0x07	0x08	0x09	0x0A	0x0B	0x0C	0x0D	0x0E	0x0F
U+037x	Ͱ	ͱ	Ͳ	ͳ	ʹ	͵	Ͷ	ͷ			ͺ	ͻ	ͼ	ͽ	;
U+038x					΄	΅	Ά	·	Έ	Ή	Ί		Ό		Ύ	Ώ
U+039x	ΐ	Α	Β	Γ	Δ	Ε	Ζ	Η	Θ	Ι	Κ	Λ	Μ	Ν	Ξ	Ο
U+03Ax	Π	Ρ		Σ	Τ	Υ	Φ	Χ	Ψ	Ω	Ϊ	Ϋ	ά	έ	ή	ί
U+03Bx	ΰ	α	β	γ	δ	ε	ζ	η	θ	ι	κ	λ	μ	ν	ξ	ο
U+03Cx	π	ρ	ς	σ	τ	υ	φ	χ	ψ	ω	ϊ	ϋ	ό	ύ	ώ	Ϗ
U+03Dx	ϐ	ϑ	ϒ	ϓ	ϔ	ϕ	ϖ	ϗ	Ϙ	ϙ	Ϛ	ϛ	Ϝ	ϝ	Ϟ	ϟ
U+03Ex	Ϡ	ϡ	Ϣ	ϣ	Ϥ	ϥ	Ϧ	ϧ	Ϩ	ϩ	Ϫ	ϫ	Ϭ	ϭ	Ϯ	ϯ
U+03Fx	ϰ	ϱ	ϲ	ϳ	ϴ	ϵ	϶	Ϸ	ϸ	Ϲ	Ϻ	ϻ	ϼ	Ͻ	Ͼ	Ͽ


	0x00	0x01	0x02	0x03	0x04	0x05	0x06	0x07	0x08	0x09	0x0A	0x0B	0x0C	0x0D	0x0E	0x0F
U+250x	─	━	│	┃	┄	┅	┆	┇	┈	┉	┊	┋	┌	┍	┎	┏
U+251x	┐	┑	┒	┓	└	┕	┖	┗	┘	┙	┚	┛	├	┝	┞	┟
U+252x	┠	┡	┢	┣	┤	┥	┦	┧	┨	┩	┪	┫	┬	┭	┮	┯
U+253x	┰	┱	┲	┳	┴	┵	┶	┷	┸	┹	┺	┻	┼	┽	┾	┿
U+254x	╀	╁	╂	╃	╄	╅	╆	╇	╈	╉	╊	╋	╌	╍	╎	╏
U+255x	═	║	╒	╓	╔	╕	╖	╗	╘	╙	╚	╛	╜	╝	╞	╟
U+256x	╠	╡	╢	╣	╤	╥	╦	╧	╨	╩	╪	╫	╬	╭	╮	╯
U+257x	╰	╱	╲	╳	╴	╵	╶	╷	╸	╹	╺	╻	╼	╽	╾	╿
