* Skola
** Nik a Julia, Denise, Thomas
** doucovanie
   prazdniny, aky rytmus
   ucebnice, pozadovane ucivo
   akou formou to prebieha, kolko hodin
   kam dat inzeraty. (skola, zastavka, obchody, lud. skola, kniznice)
   co dat do inzeratu. (trojuholnik: a^2 + b^2 = c^2, tel. nr., email, QR code?)
   cena
   aky ludia? (typ rodicov, soc. postavenie) by mali zaujem
   khanacademy, coursera - spomenut?
** ludia - anketa: co potrebuju, pouzivaju, ich prepojenie


* Java & Clojure
** clojure in emacs
#+BEGIN_SRC clojure
lein swank-wrap 4005 webcli.server
slime-connect
(let [x 1]
  (swank.core/break))
#+END_SRC


* Clojure
** persistency
   mongodb, datomic, google app engine
** AI
   nuroko.com
** recursion
   Clojure Tail Call Optimizer https://github.com/cjfrisz/clojure-tco
  
** Clojure Koans

* JVM
** see articles on root.cz
** is based on stack-based processor
** statically typed instruction set
** http://www.root.cz/clanky/pohled-pod-kapotu-jvm-5-cast-popis-virtualniho-stroje-javy/

* scala
** xml - first class support
** default get/set methods & constructor
** function & imperative
** staticlly typed
** traits (multiple inheritance)

* math
** dependency tree
** game theory
** fractals

* Kickstart - money

* Technology
** http://www.zdrojak.cz/clanky/tvorba-moderniho-e-shopu-dokonceni-uzivatelske-casti/
** Schatzsuche (geocaching), BTCs, Sequence of QR Codes/ graphical elements (pyramide, cube, sphere, toroid, etc)
** BTC - save from bitcoin.de, backup on paper
** eclipse - plugin market::  vrapper (vim-plugin) <2013-02-28 Do>
** three.js -  vytvorit gulu/gule s menami funkcii
** bootstrap-css
** CoffeeKup
   html ->
     head ->
       body ->


* People
** Susanne
   http://www.heise.de/newsticker/meldung/Junge-Akademiker-beklagen-prekaere-Arbeitsbedingungen-an-den-Unis-1922708.html
   http://www.ted.com/talks/patricia_kuhl_the_linguistic_genius_of_babies.html?fb_ref=talk
   
   Learning pronounciation
   How much of a language is silent? What does it look like when you take the silence out? (Video 2 Min)
   http://www.theverge.com/2012/7/1/3129227/silenc-project-silent-letters
   http://golancourses.net/ciid/19/silenc/

** Jan - bike tour, premiera

** Volker::
  - http://de.wikipedia.org/wiki/Open_Source_Ecology

** Thomas::
  - http://www.ted.com/talks/ayah_bdeir_building_blocks_that_blink_beep_and_teach.html
  - bicycle clickies - Thomas

** Michael::
  - http://www.ted.com/talks/matt_ridley_when_ideas_have_sex.html
  - fluidui
  - www.landoflisp.com

* youtube
** TEDxDUBLIN - Josh Klein - Hacking Work:: http://www.youtube.com/watch?v=H07pbDhBgXg
** Fake Science:: http://fakescience.tumblr.com/post/1292427190/high-fructose-corn-syrup
** Good links:: http://www.youtube.com/watch?v=i8t53Ak_yrQ
    
* Fun
** Yoda green power: http://what-if.xkcd.com/3/

* Physics:
** high school : http://hyperphysics.phy-astr.gsu.edu/hbase/hframe.html
** http://www.sixtysymbols.com/
** http://www.youtube.com/user/1veritasium


* Rick Hickey:
** TBD (To Better Do)
  - User interfaces on top of programatic interfaces
  - use composable services
  - abstractions; no bespoke protocols and formats


* TODOs
** TED conference stuff
** shackspace - docpad
** stuff to datomic - ?git has no services? http://www.youtube.com/watch?v=ROor6_NGIWU 58:00
** watch apache.org
** lighttable:: there is no source code published yet <2013-02-28 Do>
** franina - svajciarske magaziny
** Crossroad controll (3 semaphors)                                                      :clojure-script:
** vim::
  - fix <C-Bs> (on windows)
  - LLVM (c to java)
  - nailgun ** vim
  - vim scripts on JVM:: http://www.root.cz/clanky/podpora-skriptovacich-jazyku-v-jdk6-a-openjdk6/


** Pohnojit kvety
** Find a cafe with Inet
** Create experience dbase
** android app:: picture comparision
** put together:: chess ** languages ** ...
** zamerat sa na problemy tazke pre comp, lahke pre cloveka (arimaa, etc.)
** better diff - rozdiel oproti idealnemu stavu, Abstract Syntax Tree (code must be compiled for every commit)
** check changes in vundle <2013-02-28 Do>
** orgmode:
  - cheatsheet as orgmode document
  - formating with **/-/* etc.

** take a look at how to read "instance of" (see the notes from training)

* reddit, kickstarter
* time bank

* hierarchical data format
** orgmode may be it?

* sync files across computers:
** sugar sync, dropbox, ubuntu one (problem with .git)

* http://www.sme.sk/c/6414188/oprav-mi-bicykel-a-ja-ta-naucim-tancovat.html

* Peter Norvig / Stuart Russell: Artificial Intelligence: A Modern Approach

* emacs
** folding
** look at:
   org-mode: Kurt Schwer - RT 3 - emacs part 3 - org-mode and babel
   emacsrocks
   TRAMP (Transparent Remote Access, Multiple Protocols)
   use helm (former anything)
   key-chord, key-combo
   litable
   paredit
   ace-jump-mode, ace-jump-buffer

** M-1 3 C-n - scroll down 13 lines
** macros
** email: inbox too big
** magit: username, password

* dokaz identity bez udania mena

* org mode - tagging                            :org:

| col1    | col2          |
|---------+---------------|
| content | other content |
|         |               |

#+BEGIN_SRC sh :exports both
echo "Hello World" # C-c - evaluate code
#+END_SRC

#+RESULTS:
: Hello World


#+BEGIN_SRC python
return "Hello from python"
#+END_SRC

#+RESULTS:
: Hello from python

#+BEGIN_SRC clojure
(defproject my-project "0.1.0"
  :description "My great Clojure project"
  :dependencies [[org.clojure/clojure "1.1.0-alpha-SNAPSHOT"]
		 [org.clojure/clojure-contrib "1.0-SNAPSHOT"]]
  :dev-dependencies [[leiningen/lein-swank "1.0.0-SNAPSHOT"]])

(println "Hello from clojure")
#+END_SRC

#+RESULTS:
: Hello from python

** compare 2 bitmaps
#+BEGIN_SRC
// http://stackoverflow.com/questions/10487152/comparing-two-images-for-motion-detecting-purposes
private int returnCountOfDifferentPixels(String pic1, String pic2) {
        Bitmap i1 = loadBitmap(pic1);
        Bitmap i2 = loadBitmap(pic2);

        int count=0;
        for (int y = 0; y < i1.getHeight(); ++y)
               for (int x = 0; x < i1.getWidth(); ++x)
                    if (i1.getPixel(x, y) != i2.getPixel(x, y)) {
                        count++;
                    }
        return count;
    }
#+END_SRC
