* Java & Clojure: clojure in emacs
** Clojure
*** language words as a sound & tones; celular automata: cell dyies / is born: play a tone
*** AI:  nuroko.com; painting
*** recursion - Clojure Tail Call Optimizer https://github.com/cjfrisz/clojure-tco

** Java & JVM
*** Based on stack-based processor
*** Statically typed instruction set
*** http://www.root.cz/clanky/pohled-pod-kapotu-jvm-5-cast-popis-virtualniho-stroje-javy/
** scala
*** xml - first class support
*** default get/set methods & constructor
*** function & imperative
*** staticaly typed
*** traits (multiple inheritance)
*** clojuredocs - graficka reprezentacia prikladov
 #+BEGIN_SRC clojure
lein swank-wrap 4005 webcli.server
slime-connect
(let [x 1]
  (swank.core/break))
#+END_SRC
*** Rick Hickey - TBD (To Better Do)
  - User interfaces on top of programatic interfaces
  - use composable services
  - abstractions; no bespoke protocols and formats

* Math
** dependency tree
** game theory
** Markov chain (model): Market transitions http://youtu.be/o-jdJxXL_W4?t=7m3s
** fractals
   http://blog.sciencevsmagic.net/science/fractal-machine/

* Technology
** http://www.zdrojak.cz/clanky/tvorba-moderniho-e-shopu-dokonceni-uzivatelske-casti/
** Sequence of QR Codes/ graphical elements (pyramide, cube, sphere, toroid, etc.)
** BTC
*** Backup on paper
*** Curated resources https://github.com/McFrankline/Blockchain-stuff
** bootstrap-css

* People
** Susanne
   http://www.ted.com/talks/patricia_kuhl_the_linguistic_genius_of_babies.html?fb_ref=talk
   Learning pronounciation
   How much of a language is silent? What does it look like when you take the silence out? (Video 2 Min)
   http://www.theverge.com/2012/7/1/3129227/silenc-project-silent-letters
   http://golancourses.net/ciid/19/silenc/
** Volker::
  - http://de.wikipedia.org/wiki/Open_Source_Ecology
** Thomas::
  - http://www.ted.com/talks/ayah_bdeir_building_blocks_that_blink_beep_and_teach.html
  - bicycle clickies - Thomas
** Michael::
  - http://www.ted.com/talks/matt_ridley_when_ideas_have_sex.html

* OrgMode:
*** org mode - tagging                                                  :org:

| col1    | col2          |
|---------+---------------|
| content | other content |
|         |               |

#+BEGIN_SRC sh :exports both
echo "Hello World" # C-c - evaluate code
#+END_SRC

#+RESULTS:
: Hello World


#+BEGIN_SRC python
return "Hello from python"
#+END_SRC

#+RESULTS:
: Hello from python

#+BEGIN_SRC clojure
(defproject my-project "0.1.0"
  :description "My great Clojure project"
  :dependencies [[org.clojure/clojure "1.1.0-alpha-SNAPSHOT"]
         [org.clojure/clojure-contrib "1.0-SNAPSHOT"]]
  :dev-dependencies [[leiningen/lein-swank "1.0.0-SNAPSHOT"]])

(println "Hello from clojure")
#+END_SRC

#+RESULTS:
: Hello from python

*** compare 2 bitmaps
#+BEGIN_SRC
// http://stackoverflow.com/questions/10487152/comparing-two-images-for-motion-detecting-purposes
private int returnCountOfDifferentPixels(String pic1, String pic2) {
        Bitmap i1 = loadBitmap(pic1);
        Bitmap i2 = loadBitmap(pic2);

        int count=0;
        for (int y = 0; y < i1.getHeight(); ++y)
               for (int x = 0; x < i1.getWidth(); ++x)
                    if (i1.getPixel(x, y) != i2.getPixel(x, y)) {
                        count++;
                    }
        return count;
    }
#+END_SRC
*** Rest
    what is: David Allen's GTD system
    cheatsheet as orgmode document
    formating with **/-/* etc.
*** This is a headline
    Still outside the drawer
    :DRAWERNAME:
    This is inside the drawer.
    :END:
    After the drawer.
:ABC:
stuff
:END:

** Create experience dbase
** android app:: picture comparision
** put together:: chess ** languages **
** problemy tazke pre comp, lahke pre cloveka (arimaa - until 2020, etc.)
** macros

* Rest
** Syntax of log files changes (speach) sentence structure: subject comes at the end of line
** Music: what is the relation between harmony and ryth; model of musical creativity
** How represent speach context 
** time bank
** sync files across computers:
** Peter Norvig / Stuart Russell: Artificial Intelligence: A Modern Approach
** dokaz identity bez udania mena
** /usr/bin/fish findFile - ecrire un alias pour un lettre
** google lab tags http://www.chromeweblab.com/en-GB/lab-tag-explorer
** stuff to datomic - ?git has no services? http://www.youtube.com/watch?v=ROor6_NGIWU 58:00
** watch apache.org

* Lang
idioms, link sur FB, idioms - traduction + correcture
spelling glyphs
Comprehension - facile, s'exprimer - difficile
linguee.com - eu-texts
le Svejk, l'Etrangeur - examples.
